### ISSUE TITLE
Brand Assets for Socials

### ISSUE THREAD

**Issue by depatchedmode** [WalletUnCon/website#5]
Here is an:
+ avatar
+ two flavours of the banner:
    + with the wallet symbol: use this on places like Luma, where it will be the banner only
    + without the wallet symbol: use this on places like Twitter, where the banner will be shown next to the avatar

For all assets, prefer using the SVG version if possible. Feel free to request additional variants in this thread.

![avatar-400](https://github.com/WalletUnCon/website/assets/84613835/c342fba3-fec0-4fc8-be8d-b15ef3e5d326)
![avatar-400](https://github.com/WalletUnCon/website/assets/84613835/026ba19f-9c02-48e7-b05f-7d48e79c9018)
<img width="400" alt="avatar-400@2x" src="https://github.com/WalletUnCon/website/assets/84613835/2138dc27-c8d7-4be2-84fc-791d7d48c80c">
![open-graph](https://github.com/WalletUnCon/website/assets/84613835/42b8694a-b9da-4d83-95eb-a42ff20b68b6)
![open-graph](https://github.com/WalletUnCon/website/assets/84613835/5662b50d-8330-4440-a2b9-332b4ee1563f)
![twitter-banner](https://github.com/WalletUnCon/website/assets/84613835/d4e6c763-b2c3-478e-9e89-9041c96864ab)
![twitter-banner](https://github.com/WalletUnCon/website/assets/84613835/66a9a928-abec-46fe-a7ae-3313642274c8)

**Comment by ligi** [comment]
moved to the assets repo
