### ISSUE TITLE
Add an organizers page

### ISSUE THREAD

**Issue by bmann** [WalletUnCon/website#7]
We should have an organizers page that shows the humans that are volunteering to put this on. This is both recognition for eveyone's time and effort, as well as a public showcase so that people know who is involved.

Please comment with your info. You can be as anon as you like, including not including yourself :) Recommended: some social handle, at least one personal link.

- [x] @ligi info
- [x] @ulerdogan info
- [ ] @bumblefudge info
- [ ] @depatchedmode info
- [x] @kdenhartog info
- [x] @bmann info

Ulaş
* twitter @ulerdogan
* bluesky @ulas.bsky.social 
* personal link https://github.com/ulerdogan

Boris
* bluesky @bmann.ca
* farcaster @boris
* masto @boris@plnetwork.xyz
* personal link https://bmann.ca

**Comment by kdenhartog** [comment]
twitter: `@PryvitKyle`
personal link: `https://kyledenhartog.com`

**Comment by ligi** [comment]
bluesky @ligi.de
x(ex twitter) @mr_ligi
farcaster @ligi
masto @ligi@chaos.social 
personal link https://ligi.de

would be great if we do the same as we do for ETHBerlin and ProtocolBerg that we shuffle the entries - so there is no order/hierarchy

@bmann your mastodon link looks strange

**Comment by bumblefudge** [comment]
twitter: @by_caballero
masto: @by_caballero@mastodon.social

ligi it looks like GH is parsing all of our AP handles as emails and making them into mailto: links automatically !?

thanks!

**Comment by ligi** [comment]
thanks to @depatchedmode we now have this information on the site
